import Head from "next/head";
import { Container } from "../component/Container/Container";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const paymentTypes = [
  {
    name: "Card Payment",
    icon: " fa-credit-card",
  },
  {
    name: "Bank Transfer",
    icon: "fa-home",
  },
  {
    name: "Phone Transfer",
    icon: "fa-phone",
  },
  {
    name: "Bank Payment",
    icon: "fa-university",
  },
  {
    name: "USSD",
    icon: "fa-mobile",
  },
];

export default function Home() {
  const [activePaymentType, setActivePayentType] = useState(
    paymentTypes[0].name
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container className={styles.contentContainer}>
        {/* /////NAV//// */}
        <div className={styles.homePageSection}>
          <div className={styles.navSection}>
            {/* /////PAYMENT TYPE/// */}

            <div className={styles.paymentType}>
              <h3>Pay with</h3>
            </div>

            {/* /////LOGO/// */}
            <div className={styles.logo}>
              <p>Business Logo</p>
            </div>

            <div className={styles.UserEmail}>
              Macyjanet@gmail.com
              <br />
              <p className={styles.amountAvialable}>NGN 5,000.00</p>
              {/* <p className={styles.userAmount}></p> */}
            </div>
          </div>

          {/* ///////Hero/////// */}

          <div className={styles.transactionDetails}>
            <div className={styles.paymentTypeSection}>
              {paymentTypes.map((paymentType, i) => (
                <button
                  className={
                    paymentType.name === activePaymentType
                      ? styles.activePaymentType
                      : ""
                  }
                  key={`payment-type-${i}`}
                  onClick={() => setActivePayentType(paymentType.name)}
                >
                  <i className={`fa ${paymentType.icon}`}></i>
                  <span>{paymentType.name}</span>
                </button>
              ))}
            </div>

            <div className={styles.cardDetailSection}>
              <div className={styles.cardDetailHeaderSection}>
                <h2>Enter your card details</h2>
              </div>
              <div className={styles.cardDetails}>
                <div className={styles.userName}>
                  <p>Name on Card</p>
                  <input type="text" />
                </div>

                <div className={styles.cardNumber}>
                  <p>Card Number</p>
                  <input type="text" />
                </div>
                <div className={styles.cvvAndExpirySection}>
                  {" "}
                  <div className={styles.cvv}>
                    <p>CVV</p>
                    <input type="text" />
                  </div>
                  <div className={styles.expiry}>
                    <p>Expiry</p>
                    <input type="text" />
                  </div>
                </div>

                <div className={styles.buttons}>
                  <div className={styles.cancelButton}>
                    <button>Cancel</button>
                  </div>

                  <div className={styles.paymentButton}>
                    <button>Pay</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Container>

      <Container className={styles.brandingContainer}>
        Pay with Payvessel
      </Container>
    </>
  );
}
